---
engines:
  # ... CONFIG CONTENT ...
  pylint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      import-error:
        enabled: false
      syntax-error:
        enabled: false
      no-name-in-module:
        enabled: false
      similar-code:
        config:
          threshold: 16 #overriding will affect all languages
#        identical-code:
#          config:
#            threshold: #overriding will affect all languages
# ... CONFIG CONTENT ...
