---
engines:
  # ... CONFIG CONTENT ...
  pylint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      import-error:
        enabled: false
      syntax-error:
        enabled: false
# ... CONFIG CONTENT ...
