#
# An example .markdownlint-cli2.yaml file
#

# Fix any fixable errors
fix: true

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

# Define glob expressions to use (only valid at root)
globs:
  - "!*bout.md"

# Define glob expressions to ignore
ignores:
  - "ignore*.md"

# Additional paths to resolve module locations from
modulePaths:
  - "./modules"

# Disable banner message on stdout (only valid at root)
noBanner: false

# Disable inline config comments
noInlineConfig: true

# Disable progress on stdout (only valid at root)
noProgress: true

# Show found files on stdout (only valid at root)
showFound: true

config:
  # MD013 - Line length
  # https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md013.md
  tables: false
  ignore_code_blocks: true
  tables_line_length: 215
  code_block_line_length: 100