#
# An example .markdownlint-cli2.yaml file
#

# Disable some built-in rules
config:
  no-trailing-spaces: false
  no-multiple-blanks: false

# Fix any fixable errors
fix: true

# Define a custom front matter pattern
frontMatter: "<head>[^]*<\/head>"

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

# Define glob expressions to use (only valid at root)
globs:
  - "!*bout.md"

# Define glob expressions to ignore
ignores:
  - "ignore*.md"

# Additional paths to resolve module locations from
modulePaths:
  - "./modules"

# Disable banner message on stdout (only valid at root)
noBanner: true

# Disable inline config comments
noInlineConfig: true

# Disable progress on stdout (only valid at root)
noProgress: true

# Use a specific formatter (only valid at root)
outputFormatters:
  -
    - markdownlint-cli2 v0.13.0

# Show found files on stdout (only valid at root)
showFound: true

# MD013 - Line length
MD013:
  tables: false
  ignore_code_blocks: true