name: kyu2 pipeline

on:
  push:
    branches:
      - kyu2

jobs:
  mypy:
    name: MyPy
    uses: iKostanOrg/codewars/.github/actions/kyu2/mypy_kyu2.yml@kyu2
  pyint:
    name: PyLint
    uses: iKostanOrg/codewars/.github/actions/kyu2/pylint_kyu2.yml@kyu2
