---
name: Flake8 for kyu2

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - kyu2

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: 'ubuntu-24.04'
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        # This is the version of the action for setting up Python,
        # not the Python version.
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current
      # Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install flake8
      - name: Check flake8 version
        run: |
          python -m flake8 --version
      - name: Lint with flake8
        # yamllint disable rule:line-length
        # stop the build if there are Python syntax errors or undefined names
        # exit-zero treats all errors as warnings.
        # The GitHub editor is 127 chars wide
        run: |
          python -m flake8 --count --select=E9,F63,F7,F82 --doctests --show-source --statistics ./kyu_2
      - name: Complexity with flake8
        run: |
          python -m flake8 --count --benchmark --show-source --statistics ./kyu_2
        # yamllint enable rule:line-length
