---
name: PyLint for kyu5

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - kyu5

jobs:
  build:
    runs-on: 'ubuntu-24.04'
    # Adding 'timeout-minutes: 10' would prevent jobs from running
    # indefinitely if something goes wrong
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        # This is the version of the action for setting up Python,
        # not the Python version.
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install pylint
      - name: Version check
        run: |
          python -m pylint --version
      - name: Get/Export current directory
        run: |
          pwd
          export PYTHONPATH=$PYTHONPATH:./codewars
      - name: Analysing the code with pylint
        run: |
          python -m pylint -v ./kyu_5
