---
# This workflow will install Python dependencies, run tests
# and lint with a variety of Python versions
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unitest kyu3 with pytest

on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - kyu3

jobs:
  build:
    runs-on: ${{ matrix.os }}
    # Adding 'timeout-minutes: 10' would prevent jobs from running
    # indefinitely if something goes wrong
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04']
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        # This is the version of the action for setting up Python,
        # not the Python version.
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest
          python -m pip install -r requirements.txt
      - name: Version check
        run:
          python -m pytest --version
      - name: Unitest with pytest
        # yamllint disable rule:line-length
        run: |
          python -m pytest ./kyu_3 -v -rP --doctest-modules --cov-report term-missing --cov-fail-under=80 --cov=./kyu_2
        # yamllint enable rule:line-length
